### ISSUE TITLE
Addition of Sub goal on top panel

### ISSUE THREAD

**Issue by Brijbhuva** [mendezc1/GenderMagRecordersAssistant#19]
* **Description** (Example: feature to add exit button)
   -New feature: subgoal should be visible on top panel where team persona and scenario are present 
   -existing workflow: need to go back to see for which subgoal we are answering the question (Enter an action for this subgoal)

* **Describe the feature to add (or improvement)** (Example: there is no right way to exit from the application)
-subgoal on top panel where team persona and scenario are present 

* **New feature fit for the project: how does your idea fit with the aim/scope of the project?** (Example: feature gives the workflow) 
-with a new feature no need to go back to view the subgoal.

* **Merits: what are the merits of the feature?** (Example: prevent data loss)
-easy access to needed information 

* **Screenshot, if you can show something similar or a sketch.**

![subgoal](https://user-images.githubusercontent.com/2170311/44236205-07d37b80-a161-11e8-9c60-2d10080ba1a5.PNG)

* **Any other information.**
screenshot shows the new feature idea

**Comment by garayj** [comment]
Hi, I'm also an OSU student! If this is still open, can I work on this? Would this be a good issue for a first time contributor?

**Comment by roseg31** [comment]
@garayj We're actually closing this issue as it has been resolved, sorry about that
