### ISSUE TITLE
Be able to edit subgoal 

### ISSUE THREAD

**Issue by ChristopherPerdriau** [mendezc1/GenderMagRecordersAssistant#2]
Can't currently edit the subgoal and scenario after the entering the name of the first subgoal. The edit button disappears. This can hopefully be remedied by stopping the edit button from being removed and keeping whatever behavior it already has.

**Comment by ChristopherPerdriau** [comment]
<img width="437" alt="screen shot 2018-02-05 at 3 02 21 pm" src="https://user-images.githubusercontent.com/35543980/35833358-b071565e-0a85-11e8-92a3-961d781d1095.png">

**Comment by ChristopherPerdriau** [comment]
<img width="771" alt="screen shot 2018-02-05 at 3 02 32 pm" src="https://user-images.githubusercontent.com/35543980/35833373-c443b528-0a85-11e8-85e7-e762c84e3625.png">

**Comment by roseg31** [comment]
Fixed in commit a43ac42 - Added edit button and edit field to subgoal.html and edit subgoal name function to walkthrough.js based on edit functionality in prewalkthrough.js. Also updated prewalkthrough.js to hide unnecessary buttons and be able to increment subgoal count.
