### ISSUE TITLE
To Have FAQ section

### ISSUE THREAD

**Issue by Ankita-Malani** [mendezc1/GenderMagRecordersAssistant#21]
* **Description** (Example: feature to add exit button)
To Have FAQ section

* **Describe the feature to add (or improvement)** (Example: there is no right way to exit from the application)
I personally had below questions when using genderMag and I had . Users might have few types of questions when using it genderMag tools, mentioned below:
1) Why and when to use Gendermag
2) What data does excel sheet (excel stored in a local copy after using gendermag tool) depicts and how they can be used to fulfil the purpose.
3) What to mention in subgoal, how will you categorize and determine exact subgoal.

* **New feature fit for the project: how does your idea fit with the aim/scope of the project?** (Example: feature gives the workflow) 
To have FAQ section in GenderMag.org site Tabs(Besides Home, Resources, Publication etc.)

* **Merits: what are the merits of the feature?** (Example: prevent data loss)
- Quick answer to user's all query and easiness in accessing data

* **Screenshot, if you can show something similar or a sketch.**

* **Any other information.**

**Comment by garayj** [comment]
Hi, I'm an Oregon State student looking to make a contribution to an open source project. Is this still open? Would this be issue for a first time contributor?

**Comment by roseg31** [comment]
This should probably be fixed when resolving issue #12

**Comment by roseg31** [comment]
FAQ section exists, needs to be populated with more info.
