### ISSUE TITLE
Image capture is not working on header part - Windows

### ISSUE THREAD

**Issue by Ankita-Malani** [mendezc1/GenderMagRecordersAssistant#24]
* **What Operating System?**
Windows 10 Enterprise

* **What steps will reproduce the issue?**
unable to capture screenshot in header part of few page. Attaching the snapshot. 
Note:  Image capturing tool is getting hidden when you are in header section.

![Capture](https://user-images.githubusercontent.com/4867625/54869167-d7208800-4dba-11e9-9e61-0dd4bad23103.PNG)

**Comment by roseg31** [comment]
This is part of issue #3

**Comment by roseg31** [comment]
Fixed in commit 662e629
