### ISSUE TITLE
Drawing on image repeatedly shrinks screenshot

### ISSUE THREAD

**Issue by roseg31** [mendezc1/GenderMagRecordersAssistant#25]
When using the drawing tool, the screenshot of the page shrinks each time the window is closed (see example pictures)
* **What Operating System?**
Windows 10

* **What steps will reproduce the issue?**
Take screenshot with tool, select draw on image, draw something on image (optional), select save and continue, repeat drawing process to see image shrink.

* **What would you expect to be the outcome?**
Image should remain the same size 

* **All these details will help people to fix any potential bugs?**
![drawingexampleA](https://user-images.githubusercontent.com/20049970/55508259-5e1cfe00-560e-11e9-9c4b-c400bf309dca.JPG)
![drawingexampleB](https://user-images.githubusercontent.com/20049970/55508258-5e1cfe00-560e-11e9-92f7-833172e4df89.JPG)
![drawingexampleC](https://user-images.githubusercontent.com/20049970/55508256-5d846780-560e-11e9-9cc8-554c2bcb6c12.JPG)

**Comment by Brijbhuva** [comment]
commit 306ee67
