### ISSUE TITLE
CSS clipping issue

### ISSUE THREAD

**Issue by ChristopherPerdriau** [mendezc1/GenderMagRecordersAssistant#3]
On web sights, page elements with high priority clip through the Tool.

**Comment by ChristopherPerdriau** [comment]
<img width="776" alt="screen shot 2018-02-05 at 3 05 49 pm" src="https://user-images.githubusercontent.com/35543980/35833435-1c5c7736-0a86-11e8-87e0-b072d61e3a7f.png">

Arrow on the right side clips through on YouTube

**Comment by mendezc1** [comment]
Been fixed with Slideout CSS but not with pop up

**Comment by roseg31** [comment]
Currently working on this issue

**Comment by roseg31** [comment]
Update: 'cursor' used to take the screenshot can't be fixed via updated z-index & requires more attention - Can't change z-index of highlightHover without losing the ability to register click action to take screenshot (in file overlayScreen.js in function mouseMove).

**Comment by Ankita-Malani** [comment]
I think you can try clip-path or box sizing property of css to resolve css clipping issue.

**Comment by roseg31** [comment]
Fixed in commit 662e629
