### ISSUE TITLE
Unable to install tool as Chrome extension using provided instructions

### ISSUE THREAD

**Issue by kenthe3rd** [mendezc1/GenderMagRecordersAssistant#32]
* **What Operating System?**
Windows 10, using Chrome 74.0

* **What steps will reproduce the issue?**
Following installation instructions through step f) results in being unable to find the folder with the manifest file necessary for Chrome to load the extension

* **What would you expect to be the outcome?**
Expected to be able to find the folder for the tool where I downloaded the zipped file.

* **All these details will help people to fix any potential bugs?**
Found that extracting the files and navigating to the extracted folder's child folder was the one that I wanted for installing the tool's extension on Chrome.  I think that a step should be added to instruct the user to extract the contents of the zip file.

**Comment by roseg31** [comment]
Fixed with merge of PR #37
