### ISSUE TITLE
The link to the video, in how to install, in Contributing.MD points to gendermag website.

### ISSUE THREAD

**Issue by prashara** [mendezc1/GenderMagRecordersAssistant#33]
* **What Operating System?**
Windows

* **What steps will reproduce the issue?**
Click on Contributing Guide link on README.md then follow the link here (See the video at http://gendermag.org for examples of running it.)

* **What would you expect to be the outcome?**
The link should take the user directly to the video instead of the GenderMag website, this will save time and make it easier to navigate to the video.

* **All these details will help people to fix any potential bugs?**
The orignal link in contributing guide should be replaced with this link (http://gendermag.org/GenderMag%20Demonstration.mp4).

**Comment by roseg31** [comment]
Updated link in commit 48e5eeb
