### ISSUE TITLE
Ambiguous instructions on contributing to the project in Contributing.MD

### ISSUE THREAD

**Issue by prashara** [mendezc1/GenderMagRecordersAssistant#34]
* **What Operating System?**
Windows

* **What steps will reproduce the issue?**
Click on Contributing Guide link on README.md then read the instructions on how to contribute.

* **What would you expect to be the outcome?**
A first time contributor should be able to easily understand the steps and follow through them.

* **All these details will help people to fix any potential bugs?**
The instructions should be clear about which repository should be used to create a branch i.e. a cloned repository or a forked repository. In step three the phrase pop-up box should be removed.

**Comment by roseg31** [comment]
Partially resolved, transferring remaining info to issue #86
