### ISSUE TITLE
Image capture not working on Mac

### ISSUE THREAD

**Issue by ChristopherPerdriau** [mendezc1/GenderMagRecordersAssistant#5]
After clicking "click here" for screen capture and clicking a part of the webpage to take a screen capture nothing happens. Running OS High Sierra.

**Comment by Brijbhuva** [comment]
* Steps performed: 
upgraded the jquery version to 1.12.1
 
* Files affected & Commit ids: 
commit 16fbd98ed37831fac2a2b4dafd7eb647f8fcf505

* Issue tested & Verified (yes/no): 
yes 
tested on chrome browser with windows 10, macOS Mojave
