### ISSUE TITLE
Screenshot retake not working/displaying

### ISSUE THREAD

**Issue by matthecaosu** [mendezc1/GenderMagRecordersAssistant#57]
Operating System: Windows

Description: After the user is allowed to retake a screenshot, the second screenshot is not displayed in the window at all.  In addition, the retake screenshot button is not functional after the second screenshot.
![Screenshot 2019-07-03 at 9 47 19 AM](https://user-images.githubusercontent.com/52430313/60609939-94862880-9d77-11e9-9722-cc1bba74fbf2.png)

To Reproduce: Simply go through the tool until you have the option to click "Retake Screenshot".

Probable outcome: A very confused user.

**Comment by roseg31** [comment]
I'm unable to repro this issue. @Brijbhuva have you experienced this problem?

**Comment by Brijbhuva** [comment]
Checked on windows laptop and the desktop not able to reproduce the issue 
- This issue is might be a laptop specific
