### ISSUE TITLE
Team and Persona name not editable (after subgoal)

### ISSUE THREAD

**Issue by sairaja9** [mendezc1/GenderMagRecordersAssistant#62]
* **Operating System:** Windows 10

* **What steps will reproduce the issue?**
After naming the subgoal for the first time, the user no longer has the option to change the name and persona type.

* **What would you expect to be the outcome?**
The user should always have the option to edit the team name, persona name, and any other important information.

**Screenshots**

![image](https://user-images.githubusercontent.com/41133449/60614074-0c0c8580-9d81-11e9-9cc0-f351c9d6cc51.png)

![image](https://user-images.githubusercontent.com/41133449/60614097-1c246500-9d81-11e9-88b7-bcf04ce410c7.png)

![image](https://user-images.githubusercontent.com/41133449/60614111-26defa00-9d81-11e9-9c82-4a4e0e5ff7d4.png)

* **All these details will help people to fix any potential bugs?**
By having an always accessible edit button, the user will always have the chance to change important information without having to quit and restart the GenderMag session.
As shown in the first screenshot, the user is still able to change the information.  As soon as the user submits the subgoal name, he or she is no longer able to change the information at the top (screenshot #2).  Even after returning to the subgoal naming step (rename subgoal) the user still cannot change the information (screenshot #3)

**Comment by Brijbhuva** [comment]
Workflow flow issue - no issue with the tool
