### ISSUE TITLE
Inescapable Save & Exit Button (User Lock-In)

### ISSUE THREAD

**Issue by matthecaosu** [mendezc1/GenderMagRecordersAssistant#68]
OS: Windows

When you reach this page:
![Screenshot 2019-07-05 at 3 22 46 PM](https://user-images.githubusercontent.com/52430313/60747288-14a7bc00-9f39-11e9-8146-701db17e858d.png)
click the "Save and Exit" button in the top right corner of the extension. This causes the button system to lock up, resulting in a dead "Quit GenderMag" button as seen below. This makes the extension inescapable if the "Save and Exit" button is clicked on the final screen.
![Screenshot 2019-07-05 at 3 23 19 PM](https://user-images.githubusercontent.com/52430313/60747353-63edec80-9f39-11e9-9043-961e0e687459.png)

This will likely result in a very angry and frustrated consumer.
Priority: High

**Comment by roseg31** [comment]
Resolved in commit e4f055d
