### ISSUE TITLE
"None of the Above" button does not save

### ISSUE THREAD

**Issue by sairaja9** [mendezc1/GenderMagRecordersAssistant#69]
* **What Operating System?**
Windows 10

![image](https://user-images.githubusercontent.com/41133449/60747513-8af8ee00-9f3a-11e9-886b-c30ea59de7ea.png)

![image](https://user-images.githubusercontent.com/41133449/60747526-9b10cd80-9f3a-11e9-8f66-1e6d8b833994.png)

* **What steps will reproduce the issue?**
After submitting subgoal information (and selecting “None of the Above”), the box selection is not saved.  After clicking “Go Back to Subgoal”, the “None of the Above” box is not checked off.  

* **What would you expect to be the outcome?**
A user would expect this data to be saved (and recorded).

* **All these details will help people to fix any potential bugs?**
Saving results on this particular button would help.

**Comment by roseg31** [comment]
Fixed in commit 2cfa0f6
