### ISSUE TITLE
Fixes to gender pronouns within the personas

### ISSUE THREAD

**Issue by matthecaosu** [mendezc1/GenderMagRecordersAssistant#72]
As seen below, the descriptions for the different facets of the given personas specified "She/Her" for Abi  and Patricia and "He/Him" for Tim and Patrick.
![Screenshot 2019-07-10 at 9 04 11 AM](https://user-images.githubusercontent.com/52430313/60985269-0ae3d700-a2f2-11e9-8c6c-67656de515c2.png)
![Screenshot 2019-07-10 at 9 04 22 AM](https://user-images.githubusercontent.com/52430313/60985270-0ae3d700-a2f2-11e9-8c9f-2d9d103913f1.png)
![Screenshot 2019-07-10 at 9 05 02 AM](https://user-images.githubusercontent.com/52430313/60985271-0ae3d700-a2f2-11e9-926a-326d8ac36316.png)
![Screenshot 2019-07-10 at 9 05 11 AM](https://user-images.githubusercontent.com/52430313/60985272-0ae3d700-a2f2-11e9-9ef7-7335c02271fc.png)
This runs contrary to our previous inclusivity fixes, such as allowing the user to specify pronouns for their personas, and therefore should be changed to gender-neutral pronouns such as "They/Them".

**Comment by roseg31** [comment]
Updated and fixed in commit 1b0d314
