### ISSUE TITLE
Tree and Data Failure

### ISSUE THREAD

**Issue by sairaja9** [mendezc1/GenderMagRecordersAssistant#76]
* **What Operating System?**
Windows 10

![image](https://user-images.githubusercontent.com/41133449/61009985-6e3d2b80-a329-11e9-9826-46e28cd5cb08.png)

* **What steps will reproduce the issue?**
The hyperlinked tree of subgoals and actions (on the left) shows signs of failure and inconsistency.  Continuing past subgoal 3 generally presents issues such as rewriting or overwriting actions.  In addition, there is a failure to display some subgoals and actions (as shown in the screenshot above - jump from subgoal 4 to 7).  The intermediate subgoals were not displayed.  Furthermore, the “Save and Continue” and the back button fail after a certain point forcing the user to save and exit.

* **What would you expect to be the outcome?**
A user would expect to work through multiple subgoals and action without failure during a GenderMag Session

* **All these details will help people to fix any potential bugs?**
None

**Comment by Brijbhuva** [comment]
checked and it's working fine right now
