### ISSUE TITLE
At the end of the session it asks to hit the continue button, there is no Continue button.

### ISSUE THREAD

**Issue by ChristopherPerdriau** [mendezc1/GenderMagRecordersAssistant#8]
Add a continue button at the end of the session.

**Comment by Brijbhuva** [comment]
![capture](https://user-images.githubusercontent.com/2170311/44119045-e312156c-9fcc-11e8-80ac-c72e1099587c.PNG)

**Comment by Brijbhuva** [comment]
issue resolved with commit 0d66721
